[package]
name = "beans"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive", "env"] }
dirs = "6.0.0"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
